mode: dev
server:
  port: 5500
bcrypt:
  salto: 10
  secretKey: myKey
database:
  mongo:
    host: '127.0.0.1'
    user:
    port: 27017
    password:
    database: 'tienda-online'
    max: 20
    idleTimeoutMillis: 30000
    connectionTimeoutMillis: 2000
auth:
  session:
    secret: mySecretKey
    resave: false
    saveUninitialized: false
    cookie:
      secure: true
jwt:
  secretKey: tiendita
  algorithm: RS256
  expiresIn: 12h